export const freeMintControllerABI = [
   {
      type: 'constructor',
      inputs: [
         { name: '_newOwner', type: 'address', internalType: 'address' },
         { name: '_feeManager', type: 'address', internalType: 'address' },
         { name: '__feeRecipients', type: 'address[]', internalType: 'address[]' },
      ],
      stateMutability: 'nonpayable',
   },
   {
      type: 'function',
      name: 'acceptOwnership',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
   },
   {
      type: 'function',
      name: 'addFeeRecipient',
      inputs: [{ name: '_newRecipient', type: 'address', internalType: 'address' }],
      outputs: [],
      stateMutability: 'nonpayable',
   },
   {
      type: 'function',
      name: 'batchMint1155',
      inputs: [
         { name: 'collection', type: 'address', internalType: 'address' },
         { name: 'tokenIds', type: 'uint256[]', internalType: 'uint256[]' },
         { name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' },
      ],
      outputs: [],
      stateMutability: 'payable',
   },
   {
      type: 'function',
      name: 'batchMint1155To',
      inputs: [
         { name: 'collection', type: 'address', internalType: 'address' },
         { name: 'recipient', type: 'address', internalType: 'address' },
         { name: 'tokenIds', type: 'uint256[]', internalType: 'uint256[]' },
         { name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' },
      ],
      outputs: [],
      stateMutability: 'payable',
   },
   {
      type: 'function',
      name: 'getFeeRecipients',
      inputs: [],
      outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
      stateMutability: 'view',
   },
   {
      type: 'function',
      name: 'mint1155',
      inputs: [
         { name: 'collection', type: 'address', internalType: 'address' },
         { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      ],
      outputs: [],
      stateMutability: 'payable',
   },
   {
      type: 'function',
      name: 'mint1155To',
      inputs: [
         { name: 'collection', type: 'address', internalType: 'address' },
         { name: 'recipient', type: 'address', internalType: 'address' },
         { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      ],
      outputs: [],
      stateMutability: 'payable',
   },
   {
      type: 'function',
      name: 'mint721',
      inputs: [{ name: 'collection', type: 'address', internalType: 'address' }],
      outputs: [],
      stateMutability: 'payable',
   },
   {
      type: 'function',
      name: 'mint721To',
      inputs: [
         { name: 'collection', type: 'address', internalType: 'address' },
         { name: 'recipient', type: 'address', internalType: 'address' },
      ],
      outputs: [],
      stateMutability: 'payable',
   },
   {
      type: 'function',
      name: 'owner',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
   },
   {
      type: 'function',
      name: 'pendingOwner',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
   },
   {
      type: 'function',
      name: 'removeFeeRecipient',
      inputs: [{ name: '_recipient', type: 'address', internalType: 'address' }],
      outputs: [],
      stateMutability: 'nonpayable',
   },
   {
      type: 'function',
      name: 'setNewFeeManager',
      inputs: [{ name: 'newFeeManager', type: 'address', internalType: 'address' }],
      outputs: [],
      stateMutability: 'nonpayable',
   },
   {
      type: 'function',
      name: 'transferOwnership',
      inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
      outputs: [],
      stateMutability: 'nonpayable',
   },
   {
      type: 'function',
      name: 'withdrawFees',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
   },
   {
      type: 'event',
      name: 'FeeManagerUpdated',
      inputs: [
         {
            name: 'oldFeeManager',
            type: 'address',
            indexed: true,
            internalType: 'address',
         },
         {
            name: 'newFeeManager',
            type: 'address',
            indexed: true,
            internalType: 'address',
         },
      ],
      anonymous: false,
   },
   {
      type: 'event',
      name: 'FeePaid',
      inputs: [
         { name: 'collection', type: 'address', indexed: true, internalType: 'address' },
         { name: 'unitPrice', type: 'uint256', indexed: false, internalType: 'uint256' },
         { name: 'quantity', type: 'uint256', indexed: false, internalType: 'uint256' },
         { name: 'totalFee', type: 'uint256', indexed: false, internalType: 'uint256' },
      ],
      anonymous: false,
   },
   {
      type: 'event',
      name: 'FeeWithdrawn',
      inputs: [
         { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
         { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      ],
      anonymous: false,
   },
   {
      type: 'event',
      name: 'OwnershipTransferStarted',
      inputs: [
         {
            name: 'previousOwner',
            type: 'address',
            indexed: true,
            internalType: 'address',
         },
         { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
      ],
      anonymous: false,
   },
   {
      type: 'event',
      name: 'OwnershipTransferred',
      inputs: [
         {
            name: 'previousOwner',
            type: 'address',
            indexed: true,
            internalType: 'address',
         },
         { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
      ],
      anonymous: false,
   },
   {
      type: 'error',
      name: 'InvalidFee',
      inputs: [
         { name: 'expected', type: 'uint256', internalType: 'uint256' },
         { name: 'received', type: 'uint256', internalType: 'uint256' },
      ],
   },
   {
      type: 'error',
      name: 'OwnerInvalidOwner',
      inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
   },
   {
      type: 'error',
      name: 'OwnerUnauthorizedAccount',
      inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
   },
] as const
